#!/usr/bin/env sh
#
# Removes the legacy Quasar / Vue 2 tree, and moves the PWA icons where the new build
# expects them. Run once, from anywhere:
#
#     sh scripts/cleanup-legacy.sh
#
# Everything here goes through `git mv` / `git rm`, so it is staged rather than
# destroyed — `git reset --hard` puts it all back until you commit.
#
# Delete this script once it has run.

set -eu
cd "$(dirname "$0")/.."

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "Working tree has unstaged changes to tracked files."
  echo "Commit or stash them first so this stays easy to undo."
  exit 1
fi

# public/icons is generated by scripts/make-icons.py, so the old Quasar icons in
# src/statics are simply dropped rather than moved.

echo "==> Removing legacy source"
git rm -r -q \
  src/boot \
  src/store \
  src/layouts \
  src/i18n \
  src/pages \
  src/router \
  src/css \
  src/utils \
  src/statics \
  src/components/user \
  src/components/tides/Graph \
  src/components/stations/map

git rm -q \
  src/components/DateControl.vue \
  src/components/stations/Form.vue \
  src/components/stations/List.vue \
  src/components/.gitkeep \
  src/index.template.html \
  src/assets/quasar-logo-full.svg \
  src/assets/sad.svg

echo "==> Removing legacy build config"
git rm -q \
  quasar.conf.js \
  babel.config.js \
  .postcssrc.js \
  .stylintrc \
  .eslintrc.js \
  .eslintignore \
  yarn.lock

# useIsDark existed only to swap CARTO's light/dark tiles. The basemap is now Esri
# satellite, which has no dark variant, so nothing imports it any more.
if [ -f src/composables/useIsDark.ts ]; then
  echo "==> Removing the now-unused dark-mode composable"
  git rm -q src/composables/useIsDark.ts
fi

echo
echo "Done. Still to do:"
echo "  - drop the TEMPORARY legacy 'exclude' entries from tsconfig.json"
echo "  - drop the matching 'ignores' entries from eslint.config.js"
echo "  - rm scripts/cleanup-legacy.sh"
